export function Hero(){
    return (
        <div>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
            <h1>Kill me</h1>
        </div>
    );
}